(function(){
const DATA=__DCA_JSON__, ticker=document.getElementById('dcaTicker'),start=document.getElementById('dcaStart'),end=document.getElementById('dcaEnd');
Object.keys(DATA).sort().forEach(t=>{const o=document.createElement('option');o.value=t;document.getElementById('dcaTickerList').appendChild(o)});
const fmt=(x,d=2)=>Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function loadMonths(){const x=DATA[ticker.value.trim().toUpperCase()];if(!x)return;const months=x.m.map(r=>r[0]);start.innerHTML=months.map((m,i)=>`<option value="${m}" ${i===Math.max(0,months.length-120)?'selected':''}>${m}</option>`).join('');end.innerHTML=months.map((m,i)=>`<option value="${m}" ${i===months.length-1?'selected':''}>${m}</option>`).join('');}
function xirr(flows){let lo=-.99,hi=10;const npv=r=>flows.reduce((s,f)=>s+f.amount/Math.pow(1+r,f.month/12),0);if(npv(lo)*npv(hi)>0)return null;for(let i=0;i<100;i++){const mid=(lo+hi)/2;if(npv(lo)*npv(mid)<=0)hi=mid;else lo=mid;}return (lo+hi)/2;}
function calculate(){const symbol=ticker.value.trim().toUpperCase(),x=DATA[symbol];if(!x)return;const rows=x.m.filter(r=>r[0]>=start.value&&r[0]<=end.value),amount=Math.max(0,Number(document.getElementById('dcaAmount').value)||0),freq=Number(document.getElementById('dcaFrequency').value),reinvest=document.getElementById('dcaReinvest').checked,dv=Object.fromEntries(x.dv),flows=[];let shares=0,invested=0,divCash=0,divTotal=0,purchases=0;
 rows.forEach((r,i)=>{const price=r[1],div=(dv[r[0]]||0)*shares;divTotal+=div;if(reinvest&&div>0)shares+=div/price;else divCash+=div;if(i%freq===0){shares+=amount/price;invested+=amount;purchases++;flows.push({month:i,amount:-amount});}});
 if(!rows.length||!shares)return;const last=rows[rows.length-1],value=shares*last[1]+divCash,ret=value/invested-1;flows.push({month:rows.length-1,amount:value});const annual=xirr(flows),avg=invested/shares;
 const stats=[['เงินลงทุนรวม',fmt(invested)+' บาท'],['มูลค่าปัจจุบัน',fmt(value)+' บาท'],['กำไร/ขาดทุน',`${value-invested>=0?'+':''}${fmt(value-invested)} บาท`],['ผลตอบแทน',`${ret>=0?'+':''}${fmt(ret*100)}%`],['ต้นทุนเฉลี่ย',fmt(avg)+' บาท'],['จำนวนหุ้น',fmt(shares,3)],['ปันผลสะสม',fmt(divTotal)+' บาท'],['ผลตอบแทนต่อปี (XIRR)',annual===null?'—':`${annual>=0?'+':''}${fmt(annual*100)}%`]];
 document.getElementById('dcaGrid').innerHTML=stats.map(s=>`<div class="dca-stat"><small>${s[0]}</small><b>${s[1]}</b></div>`).join('');document.getElementById('dcaDetail').textContent=`${symbol} · ${rows[0][0]} ถึง ${last[0]} · ซื้อ ${purchases} งวด · ราคาล่าสุด ${fmt(last[1])} บาท · ${reinvest?'นำปันผลกลับลงทุน':'รับปันผลเป็นเงินสด'}`;document.getElementById('dcaResult').classList.add('show');}
ticker.addEventListener('change',loadMonths);ticker.addEventListener('input',()=>{if(DATA[ticker.value.trim().toUpperCase()])loadMonths()});document.getElementById('dcaCalculate').onclick=calculate;loadMonths();calculate();
})();
