(function(){
let DATA=__SWING_JSON__;const BACKTEST=__SWING_BACKTEST_JSON__, labels={triggered:'Triggered',setup:'Setup',extended:'Extended',failed:'Failed',neutral:'Neutral',illiquid:'สภาพคล่องต่ำ'};
const search=document.getElementById('swingSearch'),status=document.getElementById('swingStatus'),score=document.getElementById('swingScore'),sort=document.getElementById('swingSort'),tbody=document.getElementById('swingTable');
const n=(x,d=2)=>Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function render(){
 const q=search.value.trim().toUpperCase(), st=status.value, min=Number(score.value);
 let rows=DATA.filter(x=>(!q||x.t.includes(q))&&x.score>=min&&(st==='all'||(st==='actionable'?['triggered','setup'].includes(x.status):x.status===st)));
 const rules={score:(a,b)=>b.score-a.score,breakout:(a,b)=>Math.abs(a.breakoutPct)-Math.abs(b.breakoutPct),volume:(a,b)=>b.volumeRatio-a.volumeRatio,rr:(a,b)=>b.rr-a.rr}; rows=rows.slice().sort(rules[sort.value]);
 document.getElementById('swingCount').textContent=`พบ ${rows.length} หุ้น · Triggered ${rows.filter(x=>x.status==='triggered').length} · Setup ${rows.filter(x=>x.status==='setup').length}`;
 tbody.innerHTML=rows.map(x=>`<tr class="swing-row" data-t="${x.t}"><td class="swing-symbol">${x.t}<small>${x.date}</small></td><td><span class="swing-pill ${x.status}">${labels[x.status]}</span></td><td class="swing-score">${x.score}</td><td>${n(x.price)}</td><td>${n(x.ma20)} / ${n(x.ma50)} / ${n(x.ma200)}</td><td class="${x.breakoutPct>=0?'dir-up':''}">${x.breakoutPct>=0?'+':''}${n(x.breakoutPct)}%</td><td>${n(x.volumeRatio)}x</td><td class="${x.momentum20>=0?'dir-up':'dir-down'}">${x.momentum20>=0?'+':''}${n(x.momentum20)}%</td><td>${n(x.stop)} / ${n(x.target)}</td><td>${n(x.rr)}x</td><td class="swing-reason">${x.reasons.join(' · ')||'—'}</td></tr>`).join('');
 tbody.querySelectorAll('.swing-row').forEach(row=>row.onclick=async()=>{document.getElementById('navCycle').click();await window.ensureCycleData?.();const input=document.getElementById('cycTicker');input.value=row.dataset.t;input.dispatchEvent(new Event('change'));document.getElementById('analyzeBtn').click();});
}
function renderValidation(){const r=BACKTEST.results||{},hi=r['score70+_20d']||{},low=r['score<50_20d']||{},trigger=r.triggered_20d||{},setup=r.setup_20d||{},ts=BACKTEST.targetStop60d||{},tr=ts.triggered||{},su=ts.setup||{};const pct=(a,b,c)=>a+b+c?100*a/(a+b+c):0;const items=[['Score 70+ · ผลตอบแทนเฉลี่ย 20D',`${hi.meanPct>=0?'+':''}${n(hi.meanPct||0)}%`],['Score <50 · ผลตอบแทนเฉลี่ย 20D',`${(low.meanPct||0)>=0?'+':''}${n(low.meanPct||0)}%`],['Triggered · Target ก่อน Stop ภายใน 60D',`${n(pct(tr.targetFirst||0,tr.stopFirst||0,tr.neither||0))}%`],['Setup · Target ก่อน Stop ภายใน 60D',`${n(pct(su.targetFirst||0,su.stopFirst||0,su.neither||0))}%`]];document.getElementById('swingValidationGrid').innerHTML=items.map(x=>`<div class="validation-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');document.getElementById('swingValidationNote').textContent=`ทดสอบตั้งแต่ ${BACKTEST.startYear||'—'} สุ่มทุก ${BACKTEST.sampleStepTradingDays||'—'} วันทำการ · Triggered 20D เฉลี่ย ${(trigger.meanPct||0)>=0?'+':''}${n(trigger.meanPct||0)}% (บวก ${n(trigger.positivePct||0)}%) · Setup 20D เฉลี่ย ${(setup.meanPct||0)>=0?'+':''}${n(setup.meanPct||0)}% (บวก ${n(setup.positivePct||0)}%) · มี survivorship bias, ใช้ราคาปิด และยังไม่รวมค่าธรรมเนียม/ปันผล/slippage`;}
[search,status,score,sort].forEach(x=>x.addEventListener(x===search?'input':'change',render));
let swingLoadPromise=null;async function loadSwingData(){if(swingLoadPromise)return swingLoadPromise;const badge=document.getElementById('swingSourceStatus');swingLoadPromise=(async()=>{badge.className='feature-source-status loading';badge.textContent='Swing: กำลังโหลดข้อมูล Cloud…';let cloudError;try{const p=await fetchMarketSummary('swing');DATA=p.summary;setCloudSummaryStatus(badge,'Swing',p,DATA.length);render();return true}catch(e){cloudError=e}try{const r=await fetch(new URL('data/swing_signals.json',document.baseURI),{cache:'no-store'});if(!r.ok)throw Error(`Swing fallback HTTP ${r.status}`);DATA=await r.json();badge.className='feature-source-status fallback';badge.textContent=`Swing: ข้อมูลสำรอง ${DATA.length.toLocaleString('en-US')} หุ้น`;badge.title=cloudError.message;render();return false}catch(e){badge.className='feature-source-status error';badge.textContent='Swing: โหลดข้อมูลไม่สำเร็จ';badge.title=`${cloudError.message}; ${e.message}`;return false}})();return swingLoadPromise}document.getElementById('navSwing').addEventListener('click',loadSwingData);render();
renderValidation();
})();
