import tempfile
import unittest
from pathlib import Path

from scripts.build_toolkit_html import build


class ToolkitBuildTests(unittest.TestCase):
    def test_cycle_and_dca_payloads_are_lazy_loaded(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            output = Path(temp_dir) / "index.html"
            build(temp_dir, output)
            html = output.read_text(encoding="utf-8")

        self.assertIn("let CYCLES = {};", html)
        self.assertIn("let DATA={};", html)
        self.assertIn("fetchMarketSummary('cycles'", html)
        self.assertIn("fetchMarketSummary('dca'", html)
        self.assertIn("data/cycles_compact.json", html)
        self.assertIn("data/dca_compact.json", html)
        self.assertIn("let SIGNALS = [];", html)
        self.assertIn("let DATA=[];", html)
        self.assertIn("/v1/summaries/${name}", html)
        self.assertIn("['accumulation_signals.json','dividends.json']", html)
        self.assertIn("data/swing_signals.json", html)
        self.assertIn('class="nav-status-cluster"', html)
        for status_id in ("cycleSourceStatus", "scanSourceStatus", "swingSourceStatus", "dcaSourceStatus"):
            self.assertEqual(html.count(f'id="{status_id}"'), 1)
        self.assertNotIn('id="navCalc"', html)
        self.assertNotIn('id="pageCalc"', html)
        self.assertIn('<button class="nav-tab active" id="navScan">', html)
        self.assertIn("window.ensureCycleData = loadCloudCycles", html)
        self.assertGreaterEqual(html.count("await window.ensureCycleData?.()"), 2)
        self.assertIn("const MARKET_CACHE_NAME = 'th-stock-market-v1'", html)
        self.assertIn("async function fetchMarketSummary(name, signal)", html)
        self.assertIn("MARKET_CACHE_TTL_MS", html)
        self.assertIn("fetchMarketSummary('swing')", html)
        self.assertIn("map(name=>fetchMarketSummary(name))", html)
        self.assertIn("function setCloudSummaryStatus", html)
        self.assertIn("payload._clientSource = 'cache'", html)
        self.assertIn("เก่ากว่าวันปัจจุบัน", html)
        self.assertIn('id="recentOhlcRow"', html)
        self.assertIn("function renderRecentOhlc(stock)", html)
        self.assertIn('id="scanVolume5RatioMin"', html)
        self.assertIn("function trendInfo(s)", html)
        self.assertIn("🔎 คัดกรองหุ้น", html)
        self.assertIn("Cloud screener schema is older than this page", html)
        self.assertIn('class="table-wrap scan-table-viewport"', html)
        self.assertGreaterEqual(html.count('class="metric-help"'), 6)
        self.assertIn("buildRiseCorrectionPath}=window.DcaDomain", html)
        self.assertIn("SCENARIO_PRESETS", html)
        self.assertIn('id="riskDeclineSlider"', html)
        self.assertIn('id="riskDeclineMonthsSlider"', html)
        self.assertIn('id="riskRecoverySlider"', html)
        self.assertIn('id="riskBudgetSlider"', html)
        self.assertIn('id="budgetFitNotice"', html)
        self.assertIn('id="riskBuyMonthsSlider"', html)
        self.assertIn('id="outcomeGrid"', html)
        self.assertIn('id="riskPathModel"', html)
        self.assertIn('data-preset="rallyCorrection"', html)
        self.assertIn('id="riskRiseSlider"', html)
        self.assertIn('id="portfolioPathChart"', html)
        self.assertIn('id="portfolioChartTooltip"', html)
        self.assertIn('BE เดือน', html)
        self.assertIn('แกนซ้าย = มูลค่าเงินบาท', html)
        self.assertIn('class="dca-v2-hero"', html)
        self.assertIn('id="dcaHeroScore"', html)
        self.assertIn('id="riskLedgerExport"', html)
        self.assertIn('id="riskLedgerPeriod"', html)
        self.assertIn('class="dca-sticky-controls"', html)
        self.assertIn('class="dca-planner-columns"', html)
        self.assertIn('class="dca-scenario-column"', html)
        self.assertIn("--dca-scenario-top", html)
        self.assertIn("mockup-first information order", html)
        self.assertIn(".dca-results-column,#riskResult.show{display:contents}", html)
        self.assertIn('class="dca-results-column"', html)
        self.assertIn("@media(min-width:1680px)", html)
        self.assertIn("width:calc(100vw - 48px);max-width:none!important", html)
        self.assertIn('class="workspace-menu"', html)
        self.assertIn("rankAffordableAlternatives", html)
        self.assertIn('class="dca-advanced"', html)
        self.assertIn("version:2,budgetMode:'monthly'", html)
        self.assertIn("ซื้อขั้นต่ำ 100 หุ้นและเพิ่มทีละ 100 หุ้น", html)
        self.assertNotIn("bought=buy/price", html)
        self.assertEqual(html.count('id="stockSideMenu"'), 1)
        self.assertIn('id="cycleStockMenuOpen"', html)
        self.assertIn("window.openSharedStockMenu=openStockMenu", html)
        self.assertIn("window.getCycleTickerSymbols", html)


if __name__ == "__main__":
    unittest.main()
